### ISSUE TITLE
以太网部分的功能

### ISSUE THREAD

**Issue by lzhmwork** [fectong/Settings#1]
你好。我下载了你的代码，可以编译运行。但看到以太网部分没有功能。可以指导下吗？ 我的QQ: 453050791. 谢谢！

**Comment by fectong** [comment]
才看见, 不好意思, 不怎么看这个
以太网 ? 指的是 Ethernet 么
[LanActivity.kt](https://github.com/fectong/Settings/blob/master/app/src/main/java/com/kang1/settings/view/lan/LanActivity.kt)
这个里面只做了一个手动设置 IP, DNS, MASK 之类的简单设置, 还有个自动获取;
如果说的是拨号的话, 这边是没有代码的, 只有一个入口, 那个是内部应用了
